CREATE or replace TASK T_D_CUSTOMER
    WAREHOUSE = BIAAS_DBT_WH
    SCHEDULE =  'USING CRON 0 4 * * * Europe/Warsaw'
AS
insert into T_D_CUSTOMER 
(
	C_CUSTKEY,
	C_NAME,
	C_ADDRESS,
	C_NATIONKEY,
	C_PHONE,
	C_ACCTBAL,
	C_MKTSEGMENT,
	C_COMMENT
)
 select 
 	C_CUSTKEY,
	C_NAME,
	C_ADDRESS,
	C_NATIONKEY,
	C_PHONE,
	C_ACCTBAL,
	C_MKTSEGMENT,
	C_COMMENT
 from V_SNF_CUSTOMER;